export const GET_WEATHER_REQUEST = "GET_WEATHER_REQUEST";
export const GET_WEATHER_SUCCESS = "GET_WEATHER_SUCCESS";
export const GET_WEATHER_FAIL = "GET_WEATHER_FAIL";
export const EACH_DAY_WEATHER = "EACH_DAY_WEATHER";
